### ISSUE TITLE
Need help update webhook.yaml

### ISSUE THREAD

**Issue by hymgg** [nokia/danm#122]
**What happened**:

Need instructions / pointers on how to fill these entries in integration/manifests/webhook/webhook.yaml: caBundle, certs

k8s is 1.15.2, built using kubeadm

      # Configure your pre-generated certificate matching the details of your environment
      caBundle: <CA_BUNDLE>

    spec:
      serviceAccountName: danm-webhook
      containers:
        - name: danm-webhook
          image: 10.10.56.59:5000/my-danm:webhook-4-08052019
          command: [ "/usr/local/bin/webhook", "-tls-cert-bundle=/etc/webhook/certs/danm_webhook.crt", "-tls-private-key-file=/etc/webhook/certs/danm_webhook.key", "bind-port=8443" ]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
     # Configure the directory holding the Webhook's server certificates
      volumes:
        - name: webhook-certs
          hostPath:
            path: /etc/kubernetes/ssl/

$ kubectl apply -f integration/manifests/webhook/
serviceaccount/danm-webhook created
clusterrole.rbac.authorization.k8s.io/caas:danm-webhook created
clusterrolebinding.rbac.authorization.k8s.io/caas:danm-webhook created
service/danm-webhook-svc created
deployment.apps/danm-webhook-deployment created
Error from server (BadRequest): error when creating "integration/manifests/webhook/webhook.yaml": MutatingWebhookConfiguration in version "v1beta1" cannot be handled as a MutatingWebhookConfiguration: v1beta1.MutatingWebhookConfiguration.Webhooks: []v1beta1.MutatingWebhook: v1beta1.MutatingWebhook.ClientConfig: v1beta1.WebhookClientConfig.Service: CABundle: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|DLE\u003e","service"|..., bigger context ...|"clientConfig":{"caBundle":"\u003cCA_BUNDLE\u003e","service":{"name":"danm-webhook-svc","namespace":|...

**Environment**:

- danm version

master branch as of 08/05/2019

- Kubernetes version (use `kubectl version`):

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- danm configuration:

the only change made to integration/manifests/webhook/webhook.yaml is
"network":"default"

- OS (e.g. from /etc/os-release):

$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

- Kernel (e.g. `uname -a`):

$ uname -a
Linux mtx-huawei2-bld08 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Others:

Thanks.   -Jessica

**Comment by Levovar** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#webhookclientconfig-v1beta1-admissionregistration-k8s-io

basically the CA used in your cluster to set-up TLS with the webhook
if you did not secure webhook, or its instance certificate was signed by a root trusted CA I guess you can leave it empty

**Comment by hymgg** [comment]
Ok, thank you, haven't used webhook before.

Removed caBundle entries, then it complained about these files don't exist, of course:
"-tls-cert-bundle=/etc/webhook/certs/danm_webhook.crt", "-tls-private-key-file=/etc/webhook/certs/danm_webhook.key"

Tried remove them, so it's just, command: [ "/usr/local/bin/webhook", "bind-port=8443" ]
Failed too.
$ kubectl logs danm-webhook-deployment-84cd64568d-5ksqp -n kube-system
2019/08/08 21:20:21 ERROR: TLS configuration could not be initialized, because:open : no such file or directory

Looked at 
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

So if webhook require client auth, then apiserver itself needs to be reconfigured???
May I use the webhook without any auth?

Thanks.   -Jessica

**Comment by Levovar** [comment]
the webserver is the server in this transaction, the API server is the client.
you don't need reconfigure the API server as perse, because that's what the WebhookConfiguration API is for, and it is a dynamic API.
but yes, the admission controller feature needs to be enabled in your cluster

and no, currently there is no way to start-up an insecure webhook. I consider TLS a basic feature in my projects

**Comment by hymgg** [comment]
So don't need to do what's described here?
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers

Going by these information, looks like the 2 controllers are enabled by default?
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options

--enable-admission-plugins stringSlice
--
  | admission plugins that should be enabled in addition to default enabled ones (NamespaceLifecycle, LimitRanger, ServiceAccount, TaintNodesByCondition, Priority, DefaultTolerationSeconds, DefaultStorageClass, PersistentVolumeClaimResize, MutatingAdmissionWebhook, ValidatingAdmissionWebhook, ResourceQuota). Comma-delimited list of admission plugins: AlwaysAdmit, AlwaysDeny, AlwaysPullImages, DefaultStorageClass, DefaultTolerationSeconds, DenyEscalatingExec, DenyExecOnPrivileged, EventRateLimit, ExtendedResourceToleration, ImagePolicyWebhook, LimitPodHardAntiAffinityTopology, LimitRanger, MutatingAdmissionWebhook, NamespaceAutoProvision, NamespaceExists, NamespaceLifecycle, NodeRestriction, OwnerReferencesPermissionEnforcement, PersistentVolumeClaimResize, PersistentVolumeLabel, PodNodeSelector, PodPreset, PodSecurityPolicy, PodTolerationRestriction, Priority, ResourceQuota, SecurityContextDeny, ServiceAccount, StorageObjectInUseProtection, TaintNodesByCondition, ValidatingAdmissionWebhook. The order of plugins in this flag does not matter.

So I just need to generate the cert and key files, right?

**Comment by maxcaresywwforever** [comment]
Would it be possible to provide one script/guide to generate these: `danm_webhook.crt`, `danm_webhook.key` and `CA_BUNDLE`?

Just like what is did in [CPU-Pooler](http://github.com/nokia/CPU-Pooler)

**Comment by Levovar** [comment]
possible, yes
planned, no
feel free to contribute if you feel this is needed

but I don't consider it strictly part of the project, as it is basically plain Linux openssl stuff

@hymgg : yes, I guess these controllers are added by default. so yes, you only need to set-up TLS

**Comment by Fillamug** [comment]
Hello!

@hymgg @maxcaresywwforever I did the following, hope it helps.

First off I modified the webhook.yaml file a bit like so:
<details>
  <summary>Click to expand!</summary>

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: danm-webhook
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:danm-webhook
rules:
- apiGroups:
  - danm.k8s.io
  resources:
  - tenantconfigs
  verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:danm-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:danm-webhook
subjects:
- kind: ServiceAccount
  name: danm-webhook
  namespace: kube-system
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: danm-webhook-config
  namespace: kube-system
webhooks:
  - name: danm-netvalidation.nokia.k8s.io
    clientConfig:
      service:
        name: danm-webhook-svc
        namespace: kube-system
        path: "/netvalidation"
      # Configure your pre-generated certificate matching the details of your environment
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["danm.k8s.io"]
        apiVersions: ["v1"]
        resources: ["danmnets","clusternetworks","tenantnetworks"]
    failurePolicy: Fail
  - name: danm-configvalidation.nokia.k8s.io
    clientConfig:
      service:
        name: danm-webhook-svc
        namespace: kube-system
        path: "/confvalidation"
      # Configure your pre-generated certificate matching the details of your environment
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["danm.k8s.io"]
        apiVersions: ["v1"]
        resources: ["tenantconfigs"]
    failurePolicy: Fail
  - name: danm-netdeletion.nokia.k8s.io
    clientConfig:
      service:
        name: danm-webhook-svc
        namespace: kube-system
        path: "/netdeletion"
      # Configure your pre-generated certificate matching the details of your environment
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["DELETE"]
        apiGroups: ["danm.k8s.io"]
        apiVersions: ["v1"]
        resources: ["tenantnetworks"]
    failurePolicy: Fail
---
apiVersion: v1
kind: Service
metadata:
  name: danm-webhook-svc
  namespace: kube-system
  labels:
    danm: webhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
  selector:
    danm: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: danm-webhook-deployment
  namespace: kube-system
  labels:
    danm: webhook
spec:
  selector:
    matchLabels:
     danm: webhook
  template:
    metadata:
      annotations:
        # Adapt to your own network environment!
        danm.k8s.io/interfaces: |
          [
            {
              "network":"flannel"
            }
          ]
      name: danm-webhook
      labels:
        danm: webhook
    spec:
      serviceAccountName: danm-webhook
      containers:
        - name: danm-webhook
          image: danm_webhook
          command: [ "/usr/local/bin/webhook", "-tls-cert-bundle=/etc/webhook/certs/danm_webhook.crt", "-tls-private-key-file=/etc/webhook/certs/danm_webhook.key", "bind-port=8443" ]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
     # Configure the directory holding the Webhook's server certificates
      volumes:
        - name: webhook-certs
          hostPath:
            path: /etc/kubernetes/ssl/
```
</details>

Then I generated the cert and key files and put them into a kubernetes secret with the following webhook-create-signed-cert.sh script:
<details>
  <summary>Click to expand!</summary>

```
#!/bin/bash

set -e

usage() {
    cat <<EOF
Generate certificate suitable for use with an sidecar-injector webhook service.
This script uses k8s' CertificateSigningRequest API to a generate a
certificate signed by k8s CA suitable for use with sidecar-injector webhook
services. This requires permissions to create and approve CSR. See
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster for
detailed explantion and additional instructions.
The server key/cert k8s CA cert are stored in a k8s secret.
usage: ${0} [OPTIONS]
The following flags are required.
       --service          Service name of webhook.
       --namespace        Namespace where webhook service and secret reside.
       --secret           Secret name for CA certificate and server certificate/key pair.
EOF
    exit 1
}

while [[ $# -gt 0 ]]; do
    case ${1} in
        --service)
            service="$2"
            shift
            ;;
        --secret)
            secret="$2"
            shift
            ;;
        --namespace)
            namespace="$2"
            shift
            ;;
        *)
            usage
            ;;
    esac
    shift
done

[ -z ${service} ] && service=danm-webhook-svc
[ -z ${secret} ] && secret=danm-webhook-certs
[ -z ${namespace} ] && namespace=kube-system

if [ ! -x "$(command -v openssl)" ]; then
    echo "openssl not found"
    exit 1
fi

csrName=${service}.${namespace}
tmpdir=$(mktemp -d)
echo "creating certs in tmpdir ${tmpdir} "

cat <<EOF >> ${tmpdir}/csr.conf
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = ${service}
DNS.2 = ${service}.${namespace}
DNS.3 = ${service}.${namespace}.svc
EOF

openssl genrsa -out ${tmpdir}/server-key.pem 2048
openssl req -new -key ${tmpdir}/server-key.pem -subj "/CN=${service}.${namespace}.svc" -out ${tmpdir}/server.csr -config ${tmpdir}/csr.conf

# clean-up any previously created CSR for our service. Ignore errors if not present.
kubectl delete csr ${csrName} 2>/dev/null || true

# create  server cert/key CSR and  send to k8s API
cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

# verify CSR has been created
while true; do
    kubectl get csr ${csrName}
    if [ "$?" -eq 0 ]; then
        break
    fi
done

# approve and fetch the signed certificate
kubectl certificate approve ${csrName}
# verify certificate has been signed
for x in $(seq 10); do
    serverCert=$(kubectl get csr ${csrName} -o jsonpath='{.status.certificate}')
    if [[ ${serverCert} != '' ]]; then
        break
    fi
    sleep 1
done
if [[ ${serverCert} == '' ]]; then
    echo "ERROR: After approving csr ${csrName}, the signed certificate did not appear on the resource. Giving up after 10 attempts." >&2
    exit 1
fi
echo ${serverCert} | openssl base64 -d -A -out ${tmpdir}/server-cert.pem


# create the secret with CA cert and server cert/key
kubectl create secret generic ${secret} \
        --from-file=key.pem=${tmpdir}/server-key.pem \
        --from-file=cert.pem=${tmpdir}/server-cert.pem \
        --dry-run -o yaml |
    kubectl -n ${namespace} apply -f -
```
</details>

After this, I filled the CA bundles in the webhook.yaml file by giving this command:
```
cat ./webhook.yaml | ./webhook-patch-ca-bundle.sh > ./webhook-ca-bundle.yaml
```
Using the following webhook-patch-ca-bundle.sh script:
<details>
  <summary>Click to expand!</summary>

```
#!/bin/bash

ROOT=$(cd $(dirname $0)/../../; pwd)

set -o errexit
set -o nounset
set -o pipefail

export CA_BUNDLE=$(kubectl config view --raw -o json | jq -r '.clusters[0].cluster."certificate-authority-data"' | tr -d '"')

if command -v envsubst >/dev/null 2>&1; then
    envsubst
else
    sed -e "s|\${CA_BUNDLE}|${CA_BUNDLE}|g"
fi
```
</details>

Then I simply used the `kubectl create -f webhook-ca-bundle.yaml` command to set it up, and it works fine for me. (The only thing you need to modify still is the image you use.)
