### ISSUE TITLE
Problem with connecting pods to interfaces

### ISSUE THREAD

**Issue by Fillamug** [nokia/danm#132]
Hello!

I tried out the configuration suggested in https://github.com/nokia/danm/issues/118#issuecomment-519316180, however I still encountered some problems.

**What happened**:
First off, I changed my environment a bit, now using kube-router as the networking provider instead of flannel, however I'm still having the same vagrant vm setup with one master and two worker nodes.

Then, I tried setting up the following clusternetwork:
```
vagrant@k8s-master:~/danm_test$ cat networks/bridge_l3.yaml
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: bridge
spec:
  NetworkID: bridge_l3
  NetworkType: bridge
  Options:
    host_device: eth0
    container_prefix: bridge
    rt_tables: 250
    vlan: 100
    cidr: 10.100.50.0/24
    allocation_pool:
      start: 10.100.50.10
      end: 10.100.50.30
```
This is the CNI config I have used for it:
```
vagrant@k8s-master:/etc/cni/net.d$ cat bridge_l3.conf 
{
    "name": "mynet",
    "type": "bridge",
    "bridge": "mynet0",
    "isDefaultGateway": true,
    "forceAddress": false,
    "ipMasq": true,
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.10.0.0/16"
    },
    "cniVersion": "0.3.1"
}
```
I proceeded to check if the interface was up, and it was, however it was not supplied with an IPv4 adress, only and IPv6 one:
```
45: bridge_l3.100@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 08:00:27:c5:bc:64 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fec5:bc64/64 scope link 
       valid_lft forever preferred_lft forever
```
I assume this is what also caused the following problem, that occured when I set up this test deployment:
```
vagrant@k8s-master:~/danm_test$ cat deployments/test_de.yaml 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deployment
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"default"},
            {"clusterNetwork":"external", "ip":"dynamic"}
          ]
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        args:
        - sleep
        - "1000"
```
I checked wether or not it was connected to the interface, and it wasn't:
```
vagrant@k8s-master:~/danm_test$ kubectl get pods -o wide
NAME                              READY   STATUS    RESTARTS   AGE   IP           NODE     NOMINATED NODE   READINESS GATES
test-deployment-56c98d5c5-q59pg   1/1     Running   2          36m   10.10.1.44   node-1   <none>           <none>

vagrant@k8s-master:~/danm_test$ kubectl exec -it test-deployment-56c98d5c5-q59pg ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if80: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 8a:58:28:9b:4e:c1 brd ff:ff:ff:ff:ff:ff
    inet 10.10.1.44/24 scope global eth0
       valid_lft forever preferred_lft forever
```
**What you expected to happen**:
I expected similar results as shown in https://github.com/nokia/danm/issues/118#issuecomment-519316180.
