### ISSUE TITLE
Container interface is suffixed with increasing number globally instead of in network's scope

### ISSUE THREAD

**Issue by MaxCaresYww** [nokia/danm#153]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**:
I create pod with multiple interfaces from different networks. These interfaces are suffixed with number globally. First interface is flannel based and named as `eth0`, second interface from a tenant network with `container_prefix` configured as `internal` and it is renamed as `internal1`.

**What you expected to happen**:
I expect the first interface is named as `eth0`, and the second as `internal0`. 

**How to reproduce it**:
I use following pod yaml file
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cpupod-shared
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"tenantNetwork": "flannel","ip": "dynamic"},
            {"tenantNetwork": "internal","ip": "dynamic"}
          ]

spec:
  containers:
  - name: danm-multi-interface
    image: <image>
    command: ["/bin/sleep"]
    args: ["36000"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "100m"
        memory: 200Mi
      limits:
        cpu: "100m"
        memory: 200Mi
```

**Anything else we need to know?**:

What is the reason for this behavior. Would it be more reasonable to suffix the interface with number per network scope. In this case, the second interface then would be renamed as `internal0`. In this case, the interface name is predictable. 

**Environment**:
- danm version
- Kubernetes version (use `kubectl version`):
- danm configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:
