### ISSUE TITLE
New Network CRD object definitions assume IPv6 related parameters are mandatory

### ISSUE THREAD

**Issue by Levovar** [nokia/danm#186]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When addresses are tried to be reserved from anetwork missing V6 subnet definitions with using the latest CRD specs from main branch K8s API write operation unexpectedly fails.

**What you expected to happen**:
Update happens successfully.
**Anything else we need to know?**:
Root cause is that the complex regex in the CRD body used to validate CIDR / IP parameters are provided in a valid V6 notation do not allow "empty" value. This is against the schema, as these attributes are entirely optional.
Please don't use the latest CRD definitions directly from main until this issue is fixed!

**Comment by ckoester2** [comment]
Just to add -- the above applies to the IPv6 subnet definition, but also to the LastIp value (in both IPv4 an IPv6). Not entirely clear on whether the user is supposed to provide a LastIp value at the time a network is being defined, or if LastIp is supposed to be maintained internally but "invisible" to the user who creates the object definition. If the former (user is supposed to provide a LastIp value), then the documentation and examples should be updated to reflect that. If the latter (transparent to the user), then this regex should be optional also in IPv4.

**Comment by ckoester2** [comment]
As a workaround, it is possible to use the latest code when providing both `allocation_pool` and `allocation_pool_v6` each with a `lastIp`. Note that in this case, `net6` also needs to be provided. However, pods may still be created with WITHOUT `ip6` in the pod definition, so it is still possible to create v4-only environments.

Note that (if adding it as workaround), `lastIP` needs to be written as `address/bitmask` notation, eg.

```
    cidr: 10.240.1.0/24
    net6: fc00:01::/64
    allocation_pool:
      start: 10.240.1.100
      end: 10.240.1.200
      lastIp: 10.240.1.101/24
    allocation_pool_v6:
      start: fc00:01::100
      end: fc00:01::1000
      lastIp: fc00:01::100
```
