### ISSUE TITLE
CNI plugin error handling seems broken

### ISSUE THREAD

**Issue by ckoester2** [nokia/danm#198]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

**What happened**:

It looks like since recent commits (fd4dd7 or around that time), errors during CNI plugin execution result in a CNI crash which prevents the CNI from reporting a useful error.

I don't have a complete list of possible error scenarios (and no idea if there is no such list), but a few scenarios come to mind that I'm reasonably sure were gracefully handled with a meaningful error message before, and now just result in an unspecific error. My overall impression is that any downstream CNI plugin error, results in the DANM CNI crashing rather than cascading the error upstream.

**What you expected to happen**:

Downstream CNI plugin errors to be handled gracefully and reported upstream, so that logs / `kubectl describe` output to have useful information.

**How to reproduce it**:

Consider the following configuration (somewhat abbreviated):

```
root@debian:/home/debian/sandbox/dup-ip# cat *
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: testnet
spec:
  NetworkID: testnet
  NetworkType: macvlan
  Options:
    host_device: dummy1
    container_prefix: eth
    cidr: 10.250.1.0/24
    allocation_pool: {start: 10.250.1.100, end: 10.250.1.200}
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    danm.k8s.io/interfaces: '[{"clusterNetwork":"testnet", "ip":"10.250.1.100"}]'
spec:
  containers:
  - name: sleep
    image: sleep-infinity
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    danm.k8s.io/interfaces: '[{"clusterNetwork":"testnet", "ip":"10.250.1.100"}]'
  name: pod2
spec:
  containers:
  - name: sleep
    image: sleep-infinity
```

This is clearly an invalid configuration - both pods share the same network and same IP address.

Running the above, results in:

```
$ kubectl get pods
NAME   READY   STATUS              RESTARTS   AGE
pod1   0/1     ContainerCreating   0          6m30s
pod2   1/1     Running             0          6m30s
```

which is somewhat expected. But then, trying to troubleshoot this:

```
$ kubectl describe pod pod1
...
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               <unknown>             default-scheduler  Successfully assigned default/pod1 to debian
  Warning  FailedCreatePodSandBox  6m46s                 kubelet, debian    Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "afff4e92d21d889ea1afa11f36568e95a43cd63cc290a416e1ece90ef241b46a": netplugin failed with no error message
```

The "netplugin failed with no error message" message is where this bug report comes in. I am sure I ran into this error before by mistake, and *did* see a meaningful error pointing at the duplicate IP address.

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`): v4.1.0-42-gfd4dd71
- Kubernetes version (use `kubectl version`): 1.17.3
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:
