### ISSUE TITLE
Default Networks don't have default routes

### ISSUE THREAD

**Issue by electrocucaracha** [nokia/danm#237]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**:
The default route is not adding the default network into the routing table

```bash
$ kubectl exec -ti test -- ip route
10.244.0.0/16 via 10.244.1.1 dev eth0 
10.244.1.0/24 dev eth0 scope link  src 10.244.1.5
```

**What you expected to happen**:
```bash
$ kubectl exec -ti test -- ip route
default via 10.244.1.1 dev eth0
10.244.0.0/16 via 10.244.1.1 dev eth0 
10.244.1.0/24 dev eth0 scope link  src 10.244.1.5
```

**How to reproduce it**:
I've defined a [Default Cluster Network](https://github.com/nokia/danm/blob/master/user-guide.md#defining-default-networks) using Flannel as CNI
```bash
cat <<EOF | kubectl apply -f -
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: default
spec:
  NetworkID: flannel
  NetworkType: flannel
EOF
```
Once DANM setup is completed, I've created a single Pod with no explicit connection.
```bash
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod 
metadata:
  name: test
spec:
  containers:
    - name: test
      image: alpine:3.11
      command: ["sleep"]
      args: ["infinity"]
EOF
```
**Anything else we need to know?**:
This issue affects pods that are trying to connect to services outside of the Pod subnet(10.244.0.0/16), e. g. Kubernetes Services(10.96.0.0/12).  

**Environment**:
- DANM version (use `danm -version`): v4.2.0
- Kubernetes version (use `kubectl version`): v1.18.2
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
```
{
  "cniVersion": "0.3.1",
  "name": "danm-cni-network",
  "type": "danm",
  "kubeconfig": "/etc/cni/net.d/danm.d/kubeconfig"
}
```
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`): Linux ubuntu1804.localdomain 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Levovar** [comment]
default route not being added is usually the sign of your Flannel config being wrong. please share

also please read https://github.com/nokia/danm/issues/135

**Comment by electrocucaracha** [comment]
This was the flannel configuration file:

```yaml
{
  "name": "cbr0",
  "cniVersion": "0.3.1",
  "plugins": [
    {   
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }   
    },  
    {   
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }   
    }   
  ]
}
```
So I changed to this one
```yaml
{
  "name": "cbr0",
  "type": "flannel",
  "cniVersion": "0.3.1",
  "delegate": {
    "hairpinMode": true,
    "isDefaultGateway": true
  }
}
```
And the default routes are added
```bash
kubectl exec -ti test -- ip route
default via 10.244.1.1 dev eth0 
10.244.0.0/16 via 10.244.1.1 dev eth0 
10.244.1.0/24 dev eth0 scope link  src 10.244.1.9 
```
Thanks for the quick response on this.
