### ISSUE TITLE
DanmNets delegated to other CNI plugins are always named "eth0"

### ISSUE THREAD

**Issue by uablrek** [nokia/danm#25]
I have 2 DamnNets delegating to other CNI plugins;
```
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: default
spec:
  NetworkID: default
  NetworkType: bridge
---
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: ipvlan-orig
spec:
  NetworkID: ipvlan-orig
  NetworkType: ipvlan-orig
  container_prefix: ipv
```

Where "bridge" is the main k8s network that should be "eth0" and the "ipvlan-orig" is a renamed CNI "standard" plugin (since I can't use the built-in with cri-o #24 ).

I start a alpine pod with;
```
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "network":"default",
              "network":"ipvlan-orig"
            }
          ]
```
and enter an alpine pod with;
```
kubectl exec -it alpine-deployment-d4c99889-6znws sh
```

I expect to see the `eth0` interface connected to the bridge network and an extra interface named `ipv0` (or something similar) connected to the ipvlan but instead there is only a `eth0` interface and that is the ipvlan network. So it seems all delegated CNI plugins compete for the `eth0` name and the latest wins.
