### ISSUE TITLE
svcwatcher is not working correcly

### ISSUE THREAD

**Issue by SoulKyu** [nokia/danm#70]
**BUG REPORT**:

**What happened**:
**svcwatcher** keep in "ContainerCreating" Status.
k describe pods svcwatcher-fczh9
```
(combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e1d7c633b8b203b3264d839a608a9d028668331621c072a2e7f603e34693f761" network for pod "svcwatcher-fczh9": NetworkPlugin cni failed to set up pod "svcwatcher-fczh9_kube-system" network: CNI network could not be set up: failed to get DanmNet due to:NID:flannel in namespace:kube-system cannot be GET from K8s API server, because of error:danmnets.danm.k8s.io "flannel" not found
```

I'm using flannel avec my pods are ready : 
![image](https://user-images.githubusercontent.com/30684712/55333880-68b58700-5498-11e9-898e-f61b69fb3ec2.png)

This is my svcwatcher_ds.yml file : 
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: svcwatcher
  namespace: kube-system
spec:
  selector:
    matchLabels:
      danm.k8s.io: svcwatcher
  template:
    metadata:
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "network":"flannel"
            }
          ]
      labels:
        danm.k8s.io: svcwatcher
    spec:
      serviceAccount: svcwatcher
      dnsPolicy: ClusterFirst
      nodeSelector:
        "node-role.kubernetes.io/master": ""
      containers:
        - name: svcwatcher
          image: svcwatcher:latest
          args:
            - "--logtostderr"
      tolerations:
       - effect: NoSchedule
         operator: Exists
       - effect: NoExecute
         operator: Exists
      terminationGracePeriodSeconds: 0
```

**What you expected to happen**:

I expect svcwatcher to work correcly

**How to reproduce it**:

Install a standalone master node of kubernetes on last release of debian 9.8 with flannel. \
I use the postinstall of DANM in the README.md

Netwatcher seems to work correcly : 
![image](https://user-images.githubusercontent.com/30684712/55334434-8fc08880-5499-11e9-9561-3117a7f8f29b.png)

**Anything else we need to know?**:

**Environment**:
- danm version
3.0.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- danm configuration:
just postinstall
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux deb-k8s-02 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
```
- Others:

Just to know, is it possible to make works vlan with DANM and centos 7 which use a old kernel ?
```
Linux 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Thanks for help !! :D

**Comment by Levovar** [comment]
Yeah, you are the third people to run into this problem, so I guess I should make this explicit somewhere :)
So, the deployment manifests inside this repository are more of references to compare against, rather then "take it as-is" hard truths

In the specific case of svcwatcher, it is not like it depends on Flannel, it is just simply I use Flannel within my own environment, and I have a DanmNet called "flannel" I use.
Of course feel free to adapt the manifest to match your own environment.
The only requirement is that svcwatcher needs a network connection where it can reach the K8s API server (and that is "flannel" in my environment).

Answering the second question: VLAN - yes
IPVLAN - no (note: the two has nothing to do with each other, they are separate kernel features)

**Comment by SoulKyu** [comment]
Hi Levovar ! Thanks for reply ! 
I was miss understanding how to make works scvwatcher ^^' 

I create a damnet called flannel like this : 
```
### K8s DanmNet template ###
apiVersion: danm.k8s.io/v1
# This is a 3rd party addition to a K8s cluster.
# A DamnNet object represents a physical network together with its resources and configuration applications can use.
# The DANM will always connect K8s pods to K8s DanmNets.
kind: DanmNet
metadata:
  # Name of the K8s DanmNet object this file represents
  # MANDATORY - STRING
  name: flannel
  # The K8s namespace the network belongs to.
  # MANDATORY - STRING
  namespace: kube-system
spec:
  # This parameter will be used in application description templates for referring to a desired connection point
  # Currently this parameter shall exactly match with the name of DanmNet object itself
  # The parameter also configures which CNI configuration file is to be used if NetworkType points to a static-level CNI backend
  # MANDATORY - STRING
  NetworkID: flannel
  # This parameter, if present, denotes which backend willl be used to provision the container interfaces connected to this network.
  # Currently supported values with dynamic integration level are IPVLAN (default), SRIOV, or MACVLAN.
  # - IPVLAN option results in an IPVLAN sub-interface provisioned in L2 mode, and connected to the designated host device
  # - SRIOV option pushes a pre-allocated Virtual Function of the configured host device to the container's netns
  # - MACVLAN option results in a MACVLAN sub-interface provisioned in bridge mode, and connected to the designated host device
  # For any other CNI backend DANM reads their configuration from the configured CNI config directory (value of "CNI_CONF_DIR" environment variable, default is "/etc/cni/net.d")
  # E.g. a Pod connecting to a DanmNet with "NetworkType" set to "bridge", and "NetworkID" set to "example_network" gets an interface provisioned by the <CONFIGURED_CNI_PATH_IN_KUBELET>/bridge binary based on the <CNI_CONF_DIR>/example_network.conf file
  # The default IPVLAN backend is used when this parameter is not specified.
  # OPTIONAL - ONE OF {ipvlan,sriov,macvlan,<NAME_OF_ANY_STATIC_LEVEL_CNI_COMPLIANT_BINARY>}
  # DEFAULT VALUE: ipvlan
  NetworkType: ipvlan
  # Specific extra configuration options can be passed to the network provisioning backends.
  # Most of the parameters are only supported for level dynamic level backends, such as IPVLAN, MACVLAN, and SRIOV.
  # Other network interfaces are always provisioned based on static CNI configuration files.
  # The exceptional attributes are "rt_tables", "container_prefix", and "routes". DANM generally supports the features related to these parameters for all CNI backends.
  Options:
    # Name of the parent host device (i.e. physical host NIC).
    # Sub-interfaces are connected to this NIC in case NetworkType is set to IPVLAN, or MACVLAN.
    # Only has an effect with dynamically integrated backends. Ignored for other NetworkTypes.
    # Also ignored for SR-IOV, as the pre-allocated VF belonging to the configured Kubernetes Device pool is pushed into the connecting Pod's network namespace, regardless which Physical Funtion it belongs to.
    # OPTIONAL - STRING
    host_device: ens18
    # The IPv4 CIDR notation of the subnet associated with the network.
    # Pods connecting to this network will get their IPv4 IP from this subnet, if defined.
    # Only has an effect with dynamically integrated backends. Ignored for other NetworkTypes.
    # OPTIONAL - IPv4 CIDR FORMAT (e.g. "10.0.0.0/24")
    cidr: 10.244.0.0/16
    routes:
      10.244.0.0/16: 10.244.0.1
    rt_tables: 10000
    # Interfaces connected to this network are renamed to "container_prefix" inside the container.
    # If not provided, DANM dynamically allocates a name for each container interface belonging to this network in Pod instantiation time.
    # Generally supported parameter, works with all NetworkTypes (except where the CNI backend itself is not following the CNI standard, such is the case with Flannel).
    # Do not specify container_prefix in case multiple interfaces are provisioned from the same DanmNet.
    # OPTIONAL - STRING
    container_prefix: eth0
```

But it doesn't works ... 

Could you give me and danmnet exemple with flannel to made svcwatcher works correcly please ?

Thanks for help ! :D

**Comment by Levovar** [comment]
suggest reading-up on the network management related chapters in the documentation:
https://github.com/nokia/danm#delegating-to-other-cni-plugins

with special regards to the fact that Flannel has a static integration level, not dynamic

**Comment by SoulKyu** [comment]
Hi again,

I'm a bit confused with how i should configure network for svcwatcher, i have try to use flannel plugin direcly by setting danmnet like this : 
```
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: flannel
  namespace: kube-system
spec:
  NetworkID: flannel
  NetworkType: flannel
```
but my pods is in failed status with this error : 
```
Warning  FailedCreatePodSandBox  1s                kubelet, deb-k8s-02  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "48dd937e6b31b73dd3d01361318c82dff5e1c81af3d1246ca76583a9965fbe3f" network for pod "svcwatcher-7bc64": NetworkPlugin cni failed to set up pod "svcwatcher-7bc64_kube-system" network: CNI network could not be set up: CNI operation for network:flannel failed with:CNI delegation failed due to error:Could not load CNI config file: flannel for plugin:flannel
```

I don't understand why he cant read CNI config file because he is in the default folder /etc/cni/net.d
![image](https://user-images.githubusercontent.com/30684712/55420339-1303dc00-5577-11e9-903d-608497b3aeb3.png)
In the doc i read the file need to end by ".conf" so i have "cp" 10-flannel.conflist into 10-flannel.conflist so i have now in /etc/cni/net.d two files : 
![image](https://user-images.githubusercontent.com/30684712/55420414-47779800-5577-11e9-84e4-db74016cd8e3.png)

i have also try to use example from the folder example for svcwatcher in a namespace infra  : 
for this i have created 1 damnet called vlan150 like this : 
```
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: vlan150
  namespace: infra
spec:
  NetworkID: vlan150
  NetworkType: ipvlan
  Options:
    host_device: ens19
    container_prefix: ext
    rt_tables: 150
    vlan: 150
    cidr: 10.136.223.0/24
    allocation_pool:
      start: 10.136.223.30
      end: 10.136.223.32
```
and my svc and app like this : 
**svc**
```
apiVersion: v1
kind: Service
metadata:
  name: vnf-internal-processor
  namespace: infra
  annotations:
    danm.k8s.io/selector: '{"app":"internal-processor"}'
    danm.k8s.io/network: vlan150
spec:
  clusterIP: None
  ports:
  - name: zeromq
    port: 5555
    protocol: TCP
```

**app**
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: internal-processor
  namespace: infra
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: internal-processor
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"network":"vlan150", "ip":"dynamic"}
          ]
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        args:
        - sleep
        - "1000"
```

But my pod is crashing and never come up.
![image](https://user-images.githubusercontent.com/30684712/55420797-282d3a80-5578-11e9-8f33-34934b06f9c7.png)



Do you have more informations which can help me ? Or maybe i'm not doing this well ?

Best Regards!
