### ISSUE TITLE
Interface missing from annotations error

### ISSUE THREAD

**Issue by antalm** [nokia/danm#9]
Hi,

When the interface definition is missing from a pod's annotations, I think danm CNI plugin should return with an error indicating such issue.

```
spec:
  template:
    metadata:
      annotations:
        danm.k8s.io/interfaces: '[{"network": "flannel", "ip": "dynamic"}]'
```
Currently only the following error written by danmep's deleteDockerIface can be seen in kubelet logs, which is quite misleading.

`failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod \"my-pod-bj75q_default\": Unexpected command output ip: can't find device 'eth0'"`

Br,
Matyas
